/******************************************************************************
** Filename:    can_table.h
** Description: This files is designed for the Rx Rule table,Used to automatically
**              generated by Renesas CAN Configurator 
** Author:  Huangtingxuan
** Date: 2018.8.9
** Copyright (c) by ShangHai Ingeek Information Technology Co.Ltd
******************************************************************************/
//============================================================================
//
// CAN Rx rule table
//
//============================================================================

//============================================================================
// Includes
//============================================================================
#include "can_table.h"

//============================================================================
// Functions
//============================================================================

/******************************************************************************
** Function:    RX_RULE_TABLE_LIST
** Description: This is the Rx Rule table, automatically generated by Renesas 
**              CAN Configurator 
** Parameter:   RX_RULE_NUM
** Return:      None
******************************************************************************/
/* Rx Rule Table */
/*
Receive Rule ID Register: For the standard ID, set the ID in bits b10 to b0, ext ID: b28 to b0

Receive Rule Mask Register: set to 1--The corresponding bit is compared

Receive Rule Pointer 0 Register: 31to28 Receive Rule DLC check, receive buffer assignment

Receive Rule Pointer 1 Register: FIFO buffer assignment
*/

const can_cre_type RX_RULE_TABLE_LIST[RX_RULE_NUM] = {
/* CAN 0 reception rules */
    {0x00000010UL, 0xDFFFFFF0UL, 0x00008000UL, 0x00000001UL}, /* NO.000 : std data frm ID = H'10~1F will be accepted, destination Rx Buffer0 */
    {0x00000020UL, 0xDFFFFFF0UL, 0x00008100UL, 0x00000000UL}, /* NO.001 : std data frm ID = H'20~2F will be accepted, destination Rx Buffer1 */
    {0x00000030UL, 0xDFFFFFF0UL, 0x00008200UL, 0x00000000UL}, /* NO.002 : std data frm ID = H'30~3F will be accepted, destination Rx Buffer2 */
    {0x00000040UL, 0xDFFFFFF0UL, 0x00008300UL, 0x00000000UL}, /* NO.003 : std data frm ID = H'40~4F will be accepted, destination Rx Buffer3 */
    {0x00000050UL, 0xDFFFFFFFUL, 0x00008400UL, 0x00000000UL}, /* NO.004 : std data frm ID = H'50 will be accepted, destination Rx Buffer4 */
    {0x00000060UL, 0xDFFFFFFFUL, 0x00008500UL, 0x00000000UL}, /* NO.005 : std data frm ID = H'60 will be accepted, destination Rx Buffer5 */
    {0x00000200UL, 0xDFFFFFFFUL, 0x00000000UL, 0x00000001UL}, /* NO.006 : std data frm ID = H'200 will be accepted, destination RX FIFO buffer0 */
    {0x00000000UL, 0x00000000UL, 0x00000000UL, 0x00000001UL}, /* NO.007 : std data frm ID = H'80~8F will be accepted, destination RX FIFO buffer0 */
    
    {0x90000010UL, 0xDFFFFFF0UL, 0x00008800UL, 0x00000000UL}, /* NO.008 : Ext data frm ID = H'10000010-1F will be accepted, destination Rx Buffer8 */
    {0x90000020UL, 0xDFFFFFF0UL, 0x00008900UL, 0x00000000UL},
    {0x90000030UL, 0xDFFFFFF0UL, 0x00008a00UL, 0x00000000UL},
    {0x90000040UL, 0xDFFFFFF0UL, 0x00008b00UL, 0x00000000UL},
    
    {0x40000010UL, 0xDFFFFFF0UL, 0x00008c00UL, 0x00000000UL}, //std remote ID = H'010-1F
    {0x40000020UL, 0xDFFFFFF0UL, 0x00008d00UL, 0x00000000UL}, //std remote ID = H'020-2F 
    {0xc0000030UL, 0xDFFFFFFFUL, 0x00008e00UL, 0x00000000UL}, //ext remote ID = H'00000030
    {0xc0000040UL, 0xDFFFFFFFUL, 0x00008f00UL, 0x00000000UL}, 
	
/* CAN 1 reception rules */
    {0x00000010UL, 0xDFFFFFF0UL, 0x00009000UL, 0x00000000UL}, /* NO.000 : std data frm ID = H'10~1F will be accepted, destination Rx Buffer H10 */
    {0x00000020UL, 0xDFFFFFF0UL, 0x00009100UL, 0x00000000UL}, /* NO.001 : std data frm ID = H'20~2F will be accepted, destination Rx Buffer H11 */
    {0x00000030UL, 0xDFFFFFF0UL, 0x00009200UL, 0x00000000UL}, /* NO.002 : std data frm ID = H'30~3F will be accepted, destination Rx Buffer H12 */
    {0x00000040UL, 0xDFFFFFF0UL, 0x00009300UL, 0x00000000UL}, /* NO.003 : std data frm ID = H'40~4F will be accepted, destination Rx Buffer H13 */
    {0x00000050UL, 0xDFFFFFFFUL, 0x00009400UL, 0x00000000UL}, /* NO.004 : std data frm ID = H'50 will be accepted, destination Rx Buffer H14 */
    {0x00000060UL, 0xDFFFFFFFUL, 0x00009500UL, 0x00000000UL}, /* NO.005 : std data frm ID = H'60 will be accepted, destination Rx Buffer H15 */
    {0x00000200UL, 0xDFFFFFFFUL, 0x00000000UL, 0x00000002UL}, /* NO.006 : std data frm ID = H'200 will be accepted, destination RX FIFO buffer1 */
    {0x00000000UL, 0x00000000UL, 0x00000000UL, 0x00000002UL}, /* NO.007 : std data frm ID = H'80~8F will be accepted, destination RX FIFO buffer1 */
		//{0x00000080UL, 0xDFFFFFFFUL, 0x00009700UL, 0x00000000UL}, /* NO.007 : std data frm ID = H'80 will be accepted, destination Rx Buffer H17 */
/* CAN 2 reception rules */
    {0x00000010UL, 0xDFFFFFF0UL, 0x00009000UL, 0x00000000UL}, /* NO.000 : std data frm ID = H'10~1F will be accepted, destination Rx Buffer H10 */
    {0x00000020UL, 0xDFFFFFF0UL, 0x00009100UL, 0x00000000UL}, /* NO.001 : std data frm ID = H'20~2F will be accepted, destination Rx Buffer H11 */
    {0x00000030UL, 0xDFFFFFF0UL, 0x00009200UL, 0x00000000UL}, /* NO.002 : std data frm ID = H'30~3F will be accepted, destination Rx Buffer H12 */
    {0x00000040UL, 0xDFFFFFF0UL, 0x00009300UL, 0x00000000UL}, /* NO.003 : std data frm ID = H'40~4F will be accepted, destination Rx Buffer H13 */
    {0x00000050UL, 0xDFFFFFFFUL, 0x00009400UL, 0x00000000UL}, /* NO.004 : std data frm ID = H'50 will be accepted, destination Rx Buffer H14 */
    {0x0000006UL, 0xDFFFFFFFUL, 0x00009500UL, 0x00000000UL}, /* NO.005 : std data frm ID = H'60 will be accepted, destination Rx Buffer H15 */
    {0x00000200UL, 0xDFFFFFFFUL, 0x00000000UL, 0x00000004UL}, /* NO.006 : std data frm ID = H'200 will be accepted, destination RX FIFO buffer2 */
    {0x00000000UL, 0x00000000UL, 0x00000000UL, 0x00000004UL}, /* NO.007 : std data frm ID = H'80~8F will be accepted, destination RX FIFO buffer2 */
		//{0x00000080UL, 0xDFFFFFFFUL, 0x00009700UL, 0x00000000UL}, /* NO.007 : std data frm ID = H'80 will be accepted, destination Rx Buffer H17 */

};

