/******************************************************************************
** Filename:    can_table.h
** Description: This files is designed for the Rx Rule table,Used to automatically
**              generated by Renesas CAN Configurator 
** Author:  Huangtingxuan
** Date: 2018.8.9
** Copyright (c) by ShangHai Ingeek Information Technology Co.Ltd
******************************************************************************/
//============================================================================
//
// Header file for the CAN table rule
//
//============================================================================

#ifndef _CAN_TABLE_H_
#define _CAN_TABLE_H_

//============================================================================
// Defines
//============================================================================
#define RX_RULE_NUM_MAX              (192U)       /* Max Rx Rule number */
#define RX_RULE_PAGE_NUM             (1U)         /* Rx Rule Table page number */

#define RX_RULE_NUM                  (32U)         /* Rx Rule number */
#define RX_RULE_NUM_CH0              (16U)         /* Channel 0 Rx rule number */
#define RX_RULE_NUM_CH1              (8U)         /* Channel 1 Rx rule number */
#define RX_RULE_NUM_CH2              (8U)         /* Channel 2 Rx rule number */
#define RX_RULE_NUM_CH3              (0U)         /* Channel 3 Rx rule number */
#define RX_RULE_NUM_CH4              (0U)         /* Channel 4 Rx rule number */
/* structure */
typedef struct {
  unsigned long lword[4];
}can_cre_type;

//============================================================================
// Function defines
//============================================================================
extern const can_cre_type RX_RULE_TABLE_LIST[RX_RULE_NUM];
#endif
